### ISSUE TITLE
Occasional error with bot

### ISSUE THREAD

**Issue by IxLahiji** [dadirta/lahujDiscordBot#29]
```
Traceback (most recent call last):
  File "lahujDiscordBot.py", line 486, in <module>
    timed_command_chk()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 452, in connect
    self.ws = yield from DiscordWebSocket.from_client(self, resume=resume)
  File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 194, in from_client
    ws = yield from websockets.connect(gateway, loop=client.loop, klass=cls)
  File "/usr/local/lib/python3.5/site-packages/websockets/py35/client.py", line 19, in __await__
    return (yield from self.client)
  File "/usr/local/lib/python3.5/site-packages/websockets/client.py", line 165, in connect
    extra_headers=extra_headers)
  File "/usr/local/lib/python3.5/site-packages/websockets/client.py", line 83, in handshake
    raise InvalidHandshake("Bad status code: {}".format(status_code))
websockets.exceptions.InvalidHandshake: Bad status code: 520
Task was destroyed but it is pending!
task: <Task pending coro=<wakeup() running at lahujDiscordBot.py:46> wait_for=<Future pending cb=[Task._wakeup()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6459eeadd8>
```
After looking up issue, it appears it may be related to connection.
https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520-Web-server-is-returning-an-unknown-error

Unfortunately the error code is a general error, and does not provide enough information for us to know what exactly the cause is.

**Comment by dadirta** [comment]
`Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /usr/local/lib/python3.5/site-packages/websockets/protocol.py:408> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 414, in run
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 436, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 491, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 526, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 670, in readexactly
    block = yield from self.read(n)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 627, in read
    yield from self._wait_for_data('read')
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer`

This behaviour is discussed in this report:

https://github.com/ns-phennessy/Arcbot/issues/24
